#!/bin/bash

for loc0 in 'true false'; do
    for ns0 in 'true false'; do
        for loc1 in 'true false'; do
            for ns1 in 'true false'; do
                for loc2 in 'true false'; do
                    for ns2 in 'true false'; do
                        for loc3 in 'true false'; do
                            for ns3 in 'true false'; do
                                mcsta ../CyclicalTest.modest -E "DUR = 10, Mvar = 3, Nvar = 7, Startvar = 0, NSPRI0 = $ns0, LOCPRI0 = $loc0, NSPRI1 = $ns1, \
                                LOCPRI1 = $loc1, NSPRI2 = $ns2, LOCPRI2 = $loc2, NSPRI3 = $ns3, LOCPRI3 = $loc3" --unsafe -O Results/14$loc0$ns0$loc1$ns1$loc2$ns2$loc3$ns3.txt Minimal --props "p882, p883, p884, p885, p886, p887, p888, p889, p890, p891, p892, p893, p894, p895, p896, p897, p898, p899, p900, p901, p902, p903, p904, p905, p906, p907, p908, p909, p910, p911, p912, p913, p914, p915, p916, p917, p918, p919, p920, p921, p922, p923, p924, p925, p926, p927, p928, p929, p930, p931, p932, p933, p934, p935, p936, p937, p938, p939, p940, p941, p942, p943, p944"
                            done
                        done
                    done
                done
            done
        done
    done
done